name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  schema-generate:
    name: Schema Genearate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - uses: bahmutov/npm-install@v1
      - run: npm run schema-generate
      - run: test -z "$(git diff --name-only | grep schema.graphql)" ; exit $?

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - uses: bahmutov/npm-install@v1
      - run: npm run lint:prettier

  cspell:
    name: cspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - uses: bahmutov/npm-install@v1
      - run: npm run lint:cspell
